# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of Node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step for "build" command in commit message
      - name: Build Application
        if: contains(github.event.head_commit.message, 'build') && !contains(github.event.head_commit.message, 'build-install')
        working-directory: ./nirmata_front  # Adjust this if necessary
        run: |
          echo "Building the application..."
          npm run build --if-present        # Build the application

      # Step for "build-install" command in commit message
      - name: Build and Install Application
        if: contains(github.event.head_commit.message, 'build-install')
        working-directory: ./nirmata_front  # Adjust this if necessary
        run: |
          echo "Running npm install..."
          npm install --legacy-peer-deps  # Install dependencies
          echo "Building the application..."
          npm run build --if-present        # Build the application

      # Step for restarting PM2
      - name: Restart PM2
        if: contains(github.event.head_commit.message, 'build') || contains(github.event.head_commit.message, 'build-install')
        run: |
          export PATH=$PATH:/www/server/nodejs/v20.17.0/bin
          echo "Restarting PM2..."
          pm2 restart 0
